name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging

    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

    - uses: actions/download-artifact@v2
      with:
        name: package

    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/xylene314/numeric-app:${{ github.sha }} .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
